### PR TITLE
Code re-org

### PR DESCRIPTION
**Pull request by vihu**
Hey @ddfisher, I just wanted to get some code separation going to make it a bit easier to read and reason through the library.

Upto you if you wanna land it, there isn't any logical change here.

### CODE REVIEW

**Comment by ddfisher** [comment]
Thanks! This reorganization looks great! One small nit: my inclination is that `iter` should just be part of `encode` -- `BlockIter`'s sole purpose is to do the second half of the encoding (so it's never used anywhere else). I'm also okay with merging this as-is, though.

**Comment by JayKickliter** [comment]
> my inclination is that iter should just be part of encode

I 2nd this.

**Comment by vihu** [comment]
> Thanks! This reorganization looks great! One small nit: my inclination is that `iter` should just be part of `encode` -- `BlockIter`'s sole purpose is to do the second half of the encoding (so it's never used anywhere else). I'm also okay with merging this as-is, though.

Yup, ripped the `iter` file out and plopped it in encode, makes sense.

**Comment by ddfisher** [comment]
Looks good, thanks!

**Pull request merged**
